
app:
  datasource:
    jdbc-url: jdbc:postgresql://34.125.58.4:5432/demodb
    username: postgress
    password: password
    pool-size: 30


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
